server:
  port: 8885
  servlet:
    context-path: /app

spring:
  datasource:
    url: jdbc:h2:mem:appdb
    driverClassName: org.h2.Driver
    username: sa
    password: anypass
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  liquibase:
    change-log: classpath:database/schema-test.sql
  jmx:
    enabled: true
  batch:
    job:
      enabled: false
    hadoop:
      fsUri: hdfs://borneo:8020
      resourceManagerHost: borneo
  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:
#    user:
#      name: app
#      password: appTest
#      role: USER

management:
  endpoints:
    web:
      exposure:
        include: "hawtio,jolokia"
hawtio:
  authenticationEnabled: false