server:
  port: 9990
  servlet:
    context-path: /app

spring:
  profile: app
  datasource:
    url: jdbc:h2:mem:appdb
    driverClassName: org.h2.Driver
    username: sa
    password: anypass
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  security:
    user:
      name: app
      password: appTest
  jmx:
    enable: true
